site_name: Ivan Docs
##site_url: 'https://midominio.com'
site_author: 'Iván Vidal'
site_description: 'Practica Mkdocks explicando asignaturas del modulo DAW y sobre mi.'

theme:
  features:
    - content.action.edit
    - content.action.view
#    - navigation.tabs
#    - navigation.tabs.sticky
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Roboto'
  google_analytics:
    property: 'UA-12345678-9'
    auto: true

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false

extra_css:
  - 'css/style.css'

extra_javascript:
  - js/script.js

nav:
  - Home: index.md
  - Sobre mi: about.md
  - Programacion: programacion.md
  - Bases de datos: basesdedatos.md
  - Entornos de desarrollo: entornos.md
  - Lenguajes de marcas: lenguajes.md
  - Sistemas informaticos: sistemas.md
  - Ingles: ingles.md
  - Itinerario Personal: itinerario.md
  - Proyecto Intermodular: pintermodular.md

repo_url: 'https://github.com/ivanviidaal/practicamkdocs.git'
repo_name: 'GitHub'
edit_uri: 'edit/main/docs/'

use_directory_urls: true
strict: true
